USE QLDA
GO
DECLARE @TonSoPhongBan INT
SELECT @TonSoPhongBan = SUM(MAPHG)FROM dbo.PHONGBAN
PRINT N'tổng số phòng ban là: '+CAST(@TonSoPhongBan AS NVARCHAR)
PRINT N'tổng số phòng ban là: '+CONVERT(NVARCHAR,@TonSoPhongBan)
GO
DECLARE @thongTin TABLE (MANV NVARCHAR(9),tongTG FLOAT)
INSERT INTO @thongTin
SELECT MANV, SUM(THOIGIAN) 
FROM dbo.NHANVIEN JOIN  dbo.PHANCONG ON PHANCONG.MA_NVIEN = NHANVIEN.MANV
GROUP BY MANV

SELECT [@thongTin].MANV
,UPPER(LEFT(tenNV,1))+SUBSTRING(tenNV,2,LEN(tenNV)-1) AS vietHoaTenNV,
CONVERT(VARCHAR,GETDATE(),101) AS ngSinh , DATEDIFF(YEAR,ngsinh,GETDATE()) AS tuoi,tongTG
FROM @thongTin JOIN dbo.NHANVIEN ON NHANVIEN.MANV = [@thongTin].MANV 
GO

