USE QLDA
GO
SELECT TENDEAN,CAST(SUM(THOIGIAN) AS DECIMAL(6,2) ) FROM dbo.PHANCONG JOIN dbo.DEAN ON DEAN.MADA = PHANCONG.MADA
GROUP BY TENDEAN
SELECT TENDEAN,CONVERT(NVARCHAR, SUM(THOIGIAN)) FROM dbo.PHANCONG JOIN dbo.DEAN ON DEAN.MADA = PHANCONG.MADA
GROUP BY TENDEAN

SELECT TENDEAN,REPLACE(CAST(AVG(THOIGIAN) AS DECIMAL(6,2) ),'.',',') FROM dbo.PHANCONG JOIN dbo.DEAN ON DEAN.MADA = PHANCONG.MADA
GROUP BY TENDEAN

--bai2

SELECT TENDEAN,CEILING(CAST(AVG(THOIGIAN) AS DECIMAL(6,2) )) FROM dbo.PHANCONG JOIN dbo.DEAN ON DEAN.MADA = PHANCONG.MADA
GROUP BY TENDEAN
SELECT TENDEAN,FLOOR(CAST(AVG(THOIGIAN) AS DECIMAL(6,2) )) FROM dbo.PHANCONG JOIN dbo.DEAN ON DEAN.MADA = PHANCONG.MADA
GROUP BY TENDEAN



SELECT HONV,TENLOT,TENNV , ROUND(LUONG,2) AS'luong' FROM dbo.NHANVIEN
WHERE LUONG > (SELECT AVG(LUONG) FROM dbo.NHANVIEN
WHERE PHG IN (SELECT MAPHG FROM dbo.PHONGBAN
WHERE TENPHG = N'nghiên cứu'))  

--bai3

SELECT UPPER(HONV),
LOWER(TENLOT),
LOWER(LEFT(TENNV,1)) + UPPER(SUBSTRING(TENNV,2,1))+LOWER(SUBSTRING(TENNV,3,LEN(TENNV))),
SUBSTRING(DCHI,CHARINDEX(' ',DCHI)+1,CHARINDEX(',',DCHI)-CHARINDEX(' ',DCHI)-1),
COUNT(MA_NVIEN) AS sl 
FROM dbo.NHANVIEN JOIN dbo.THANNHAN ON THANNHAN.MA_NVIEN = NHANVIEN.MANV
GROUP BY HONV,TENLOT,TENNV,DCHI
HAVING COUNT(MA_NVIEN) > 2

DECLARE @tk TABLE (MaPHG INT,tp INT, sl INT)
INSERT INTO @tk
SELECT phg, MA_NQL ,COUNT(MANV)  FROM dbo.NHANVIEN
GROUP BY PHG,MA_NQL
DECLARE @max INT
SELECT @max = MAX(sl) FROM @tk
SELECT TENPHG as N'Tên Phòng', (HONV + ' ' + TENLOT + ' ' + TENNV ) as N'Trưởng Phòng', 'Fpoly'
FROM dbo.PHONGBAN 
JOIN (SELECT * FROM @tk WHERE sl = @max) a ON a.MaPHG = PHONGBAN.MAPHG
JOIN dbo.NHANVIEN ON a.tp = dbo.NHANVIEN.MANV
GO

--cau 4
SELECT * FROM dbo.NHANVIEN
WHERE YEAR(NGSINH) =1960 OR YEAR(NGSINH) = 1965

SELECT *,DATEDIFF(YEAR,NGSINH,GETDATE()) tuoi FROM dbo.NHANVIEN

SELECT *,DATENAME(WEEKDAY,NGSINH) FROM dbo.NHANVIEN

SELECT COUNT(MANV) soLuong,TENNV,CONVERT(VARCHAR,NG_NHANCHUC,105) AS ngaync
FROM dbo.NHANVIEN JOIN dbo.PHONGBAN ON PHONGBAN.MAPHG = NHANVIEN.PHG
GROUP BY TENNV,CONVERT(VARCHAR,NG_NHANCHUC,105)
