CREATE DATABASE QLNS
GO
USE QLNS
GO
CREATE TABLE Coso(
Macs VARCHAR(10) PRIMARY KEY NOT NULL,
TenCs NVARCHAR(30)
)
CREATE TABLE CongNhan(
ID VARCHAR(10) NOT NULL,
Hoten NVARCHAR(30) NOT NULL,
Gtinh NVARCHAR(30),
Dchi NVARCHAR(30),
Luong MONEY,
PRIMARY KEY(ID,Macs),
Macs VARCHAR(10) REFERENCES dbo.Coso(Macs)
)
CREATE TABLE NguoiPhuThuoc(
Macs VARCHAR(10) NOT NULL,
ID VARCHAR(10) NOT NULL ,
SoLuong INT,
NgayDK DATE,
PRIMARY KEY(Macs,ID),
foreign key (Macs, ID) references dbo.CongNhan (Macs,ID)
)